# Generated by Django 5.1 on 2024-08-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteleria', '0002_alter_cliente_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tortas',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
